id: A52833855
title: Prayer to Chökyi Wangpo, the Bodhisattva and Tamer of Beings
type: translation
pechas:
- I39BF88A8
- I4669D94A
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:35:21.730601
  last_modified_at: 2023-01-04 12:35:21.730607
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I39BF88A8/6DD3: D734
  I4669D94A/0871: D734
